apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-large-data-sharing-golang-webapp-display
spec:
  info:
    title: Large data sharing Golang web app
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-large-data-sharing-golang-webapp.git
      sourceType: git
  ui:
    input:
      variables:
        bucket_location:
          name: bucket_location
          title: Bucket Location
        disable_services_on_destroy:
          name: disable_services_on_destroy
          title: Disable Services On Destroy
        init:
          name: init
          title: Init
        labels:
          name: labels
          title: Labels
        lds_client_image:
          name: lds_client_image
          title: Lds Client Image
        lds_firestore:
          name: lds_firestore
          title: Lds Firestore
        lds_firestore_field_name:
          name: lds_firestore_field_name
          title: Lds Firestore Field Name
        lds_firestore_field_orderNo:
          name: lds_firestore_field_orderNo
          title: Lds Firestore Field OrderNo
        lds_firestore_field_path:
          name: lds_firestore_field_path
          title: Lds Firestore Field Path
        lds_firestore_field_size:
          name: lds_firestore_field_size
          title: Lds Firestore Field Size
        lds_firestore_field_tags:
          name: lds_firestore_field_tags
          title: Lds Firestore Field Tags
        lds_initialization_archive_file_name:
          name: lds_initialization_archive_file_name
          title: Lds Initialization Archive File Name
        lds_initialization_bucket_name:
          name: lds_initialization_bucket_name
          title: Lds Initialization Bucket Name
        lds_server_image:
          name: lds_server_image
          title: Lds Server Image
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
